### ISSUE TITLE
Error when signing in or adding plugin

### ISSUE THREAD

**Issue by mathiascode** [cuberite/plugin-repository#46]
![Screenshot](https://user-images.githubusercontent.com/8754153/77824361-d7a8d880-710a-11ea-9524-355b71f568f5.png)

```
<br />
<b>Fatal error</b>:  Uncaught Exception: For URL: https://api.github.com/repositories/24958719/hooks?client_id=<snip>&amp;client_secret=<snip>&lt;br&gt;Response: Array
(
    [message] =&gt; Not Found
    [documentation_url] =&gt; https://developer.github.com/v3/repos/hooks/#create-a-hook
)
&lt;br&gt;Curl error (0):  in D:\home\site\Composer\vendor\flexyproject\githubapi\lib\GitHub\AbstractApi.php:590
Stack trace:
#0 [internal function]: FlexyProject\GitHub\AbstractApi-&gt;FlexyProject\GitHub\{closure}()
#1 D:\home\site\Composer\vendor\flexyproject\curl\Client.php(203): call_user_func_array()
#2 D:\home\site\Composer\vendor\flexyproject\curl\Client.php(189): FlexyProject\Curl\Client-&gt;_call()
#3 D:\home\site\Composer\vendor\flexyproject\githubapi\lib\GitHub\AbstractApi.php(596): FlexyProject\Curl\Client-&gt;perform()
#4 D:\home\site\wwwroot\Environment Interfaces\GitHub API\Repositories.php(141): FlexyProject\GitHub\AbstractApi-&gt;request()
#5 D:\home\site\wwwroot\Add.php(36): GitHubAPI\Repositories::CreateUpdateH in <b>D:\home\site\Composer\vendor\flexyproject\githubapi\lib\GitHub\AbstractApi.php</b> on line <b>590</b><br />
```

**Comment by tigerw** [comment]
It seems like it falls over if a user adds a plugin without administrator rights to the repository, since adding the webhook fails.

**Comment by tigerw** [comment]
Additionally strict xhtml fails when it prints errors.

**Comment by tigerw** [comment]
Thanks for the report! Would you have a snip of the error when logging in?

**Comment by bearbin** [comment]
It also generates a very similar error when trying to delete a plugin.

**Comment by mathiascode** [comment]
Doesn't seem like I can get the error to show up when signing in anymore.
